fields:
  - type: compositefield
    caption: Version
    defaultMargins: 0 10 0 0
    items:
      - type: list
        name: version
        values:
          - value: v1.20.4
            caption: v1.20.4
          - value: v1.19.8
            caption: v1.19.8
          - value: v1.18.16
            caption: v1.18.16
        default: v1.19.8
        hideLabel: false
        editable: false
        width: 155

      - type: displayfield
        markup: K8s Dashboard
        width: 113
        cls: x-form-item-label
        margins: 0 11 0 0

      - name: dashboard
        type: list
        width: 155
        values:
          general: v2
          k8dash: K8Dash
        default: general
        hideLabel: false
        editable: false

  - type: compositefield
    name: topo
    caption: Topology
    defaultMargins: 0 10 0 0
    items:
      - type: list
        value: 0-dev
        width: 155
        values:
          - value: 0-dev
            caption: Development
            tooltip: One master (1) and one scalable worker (1+)

          - value: 1-prod
            caption: Production
            tooltip: Multi master (3) with API balancers (2+) and scalable workers (2+)

      - type: displayfield
        markup: Ingress Controller
        cls: x-form-item-label
        width: 113
        margins: 0 11 0 0

      - name: ingress-controller
        type: list
        width: 155
        margins: 0 10 0 0
        values:
          Nginx: NGINX
          HAProxy: HAProxy
          Traefik: Traefik
        default: Nginx
        hideLabel: false
        editable: false

  - type: displayfield
    cls: warning
    height: 30
    hideLabel: true
    hidden: true
    markup:

  - name: deploy
    type: radiolist
    caption: Deployment
    columns: 3
    values:
      - value: cc
        caption: Clean cluster
        tooltip:
          text: Clean cluster with pre-deployed HelloWorld example
          maxWidth: 210
          y: -1
      - value: cmd
        caption: Custom
        tooltip:
          text: Deploy custom helm or stack via shell command
          maxWidth: 165
          y: -1

    default: cc
    showIf:
      cmd:
        name: cmd
        type: text
        height: 65
        required: true
        hideLabel: true
        default: |-
          OPERATOR_NAMESPACE=open-liberty
          kubectl create namespace "$OPERATOR_NAMESPACE"
          kubectl apply -f https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.0/openliberty-app-crd.yaml
          curl -L https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.0/openliberty-app-cluster-rbac.yaml | sed -e "s/OPEN_LIBERTY_OPERATOR_NAMESPACE/${OPERATOR_NAMESPACE}/"  | kubectl apply -f -
          curl -L https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.0/openliberty-app-operator.yaml  | sed -e "s/OPEN_LIBERTY_WATCH_NAMESPACE/${OPERATOR_NAMESPACE}/"  | kubectl apply -n ${OPERATOR_NAMESPACE} -f -
          kubectl apply -f https://raw.githubusercontent.com/jelastic-jps/kubernetes/${settings.version}/addons/open-liberty.yaml

  - type: toggle
    name: storage
    caption: NFS Storage
    tooltip: Attach dedicated NFS Storage with dynamic volume provisioning
    value: true
    showIf:
      true:
        - type: compositefield
          caption: Modules
          pack: start
          items:
            - type: checkbox
              name: monitoring
              caption: Prometheus & Grafana

            - type: checkbox
              name: jaeger
              caption: Jaeger Tracing Tools
              margins: 0 0 0 25

      false:
        - type: compositefield
          caption: Modules
          pack: start
          items:
            - type: checkbox
              name: monitoring
              caption: Prometheus & Grafana
              value: false
              disabled: true

            - type: checkbox
              name: jaeger
              caption: Jaeger Tracing Tools
              value: false
              disabled: true
              margins: 0 0 0 25

  - type: compositefield
    pack: start
    items:
      - type: checkbox
        name: api
        caption: Remote API Access
        value: false

  - type: displayfield
    height: 10
    hideLabel: true
    markup:

  - type: envname
    name: envName
    caption: Environment
    dependsOn: region
    randomName: true
    showFullDomain: true
    required: true

  - type: string
    name: displayName
    caption: Display Name
    default: Kubernetes Cluster

  - type: regionlist
    name: region
    caption: Region
    disableInactive: true
    selectFirstAvailable: true
    filter:
      type: ["vz7"]
      isActive: true